### ISSUE TITLE
exportModel error

### ISSUE THREAD

**Issue by mascencio27** [SysBioChalmers/RAVEN#378] opened 2021-11-02 16:42 UTC
### Description of the issue:

When trying to export the Raven format model to xml with the function (exportModel(modelRAVEN2,'reh16_V10.xml',1,0) it generates the following errors:

WARNING: There is no unconstrained field in the model structure. This means that no metabolites are considered exchange metabolites

WARNING: The "inchis" field must be a cell array of strings

WARNING: The "rxnReferences" field must be a cell array of strings

WARNING: The model contains empty reaction IDs

WARNING: The following reaction IDs are duplicates:
	
Array indices must be positive integers or logical values.

Error in checkModelStruct (line 228)
metInComp=strcat(model.metNames,'[',model.comps(model.metComps),']');

Error in exportModel (line 68)
    checkModelStruct(model,false);

Error in exportModelxml (line 13)
exportModel(modelRAVEN2,'reh16_V10.xml',1,0);

I have tried including vectors such as:
modelRAVEN2.id = char("raeu");
modelRAVEN2.description = char("ralstonia eutropha");
modelRAVEN2.annotation = struct();
modelRAVEN2.rxnMiriams = cell(2911,1);
modelRAVEN2.rxnReferences = cell(2911,1);
%modelRAVEN2.rxnConfidenceScores = double(2911);
modelRAVEN2.geneShortNames= cell(1584,1);
modelRAVEN2.inchis= cell(1860,1);

But, the error is same

#### Reproducing this issue:

```MatLab
clear
solverOK = changeCobraSolver('glpk','LP');
modelCOBRA=readCbModel('reh16_gapfilled_cobra_V10.xls');
modelRAVEN2=ravenCobraWrapper(modelCOBRA);
modelRAVEN2.id = char("raeu");
modelRAVEN2.description = char("ralstonia eutropha");
modelRAVEN2.annotation = struct();
modelRAVEN2.rxnMiriams = cell(2911,1);
modelRAVEN2.rxnReferences = cell(2911,1);
%modelRAVEN2.rxnConfidenceScores = double(2911);
modelRAVEN2.geneShortNames= cell(1584,1);
modelRAVEN2.inchis= cell(1860,1);
exportModel(modelRAVEN2,'reh16_V10.xml',1,0);
```

#### System information
* Please report:
1. RAVEN version (stabile [release](https://github.com/SysBioChalmers/RAVEN/releases), `devel` branch?)
2. Operating system (Windows 10)

**I hereby confirm that I have:**
- [x ] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [x ] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by edkerk** [comment] 2021-11-02 22:22
1. Could you please specify which RAVEN version you're using?

2. There is a warning about non-unique reaction identifiers. What is the output of `modelRAVEN2.rxns(duplicates(modelRAVEN2.rxns))`?

3. Then, there are warnings about `inchis` and `rxnReferences` (I'm not sure why you also add other empty fields when you try to resolve the problem). What is the output of:
```
class(modelRAVEN2.inchis)
size(modelRAVEN2.inchis)
modelRAVEN2.inchis(1)

class(modelRAVEN2.rxnReferences)
size(modelRAVEN2.rxnReferences)
modelRAVEN2.rxnReferences(1)
```

4. In your solution, you try to generate empty fields. However, `rxnReferences`, `inchis`, `rxnMiriams`, `geneShortNames` and `annotation` are [not compulsory](https://github.com/SysBioChalmers/RAVEN/wiki/RAVEN-Model-Structure). If you do not care about their content, then it would be better to remove these fields instead (`modelRAVEN2= rmfield(modelRAVEN2,'inchis');`.

**Comment by mascencio27** [comment] 2021-11-03 13:59
Thanks Eduard!
THE RAVEN TOOLBOX v.2.4.0

**Comment by edkerk** [comment] 2021-11-03 14:54
The problem is with `readCbModel` that seems to write empty doubles instead of empty strings, probably specifically when reading XLS format. This is part of COBRA Toolbox, not RAVEN.

But as I wrote above, if you do not care about the content fields you can just remove them (maybe these fields are completely empty anyway?). Otherwise you'd have to manually populate those fields, there are no dedicated function for this. Maybe it will work to replace all empty doubles with empty strings using `modelRAVEN2.rxnReferences(cellfun(@isempty,modelRAVEN2.rxnReferences))={''};`

Regarding repeated identifiers, try:
```
[~,b]=unique(modelRAVEN2.rxns);
modelRAVEN2.rxns(setdiff(1:numel(modelRAVEN2.rxns),b))
```

**Comment by mascencio27** [comment] 2021-11-03 15:10
Thanks you for your answer.

I tried again and it shows the same error :(

WARNING: There is no unconstrained field in the model structure. This means that no metabolites are considered exchange metabolites

WARNING: The "inchis" field must be a cell array of strings

WARNING: The model contains empty reaction IDs

WARNING: The following reaction IDs are duplicates:
	

Array indices must be positive integers or logical values.

Error in checkModelStruct (line 228)
metInComp=strcat(model.metNames,'[',model.comps(model.metComps),']');

Error in exportModel (line 68)
    checkModelStruct(model,false);

Error in exportModelxml (line 16)
exportModel(modelRAVEN2,'reh16_V10.xml',1,0);

**Comment by edkerk** [comment] 2021-11-03 20:01
Also try the [latest RAVEN version](https://github.com/SysBioChalmers/RAVEN/releases) (2.5.3).

What does `modelRAVEN2.metComps` contain, maybe print the output of `modelRAVEN2.metComps(1:10)`, or does `class(modelRAVEN2.metComps)` give the output 'double'?

Empty reaction IDs is problematic (I missed that in your first message), `find(cellfun(@isempty, modelCOBRA))` will give you with reactions do not have IDs.

**Comment by mascencio27** [comment] 2021-11-03 21:12
Thanks you for your response.

I resolve the inconvenient with the arrays, but, now the error is:

typecode =

    'fbc_objective'


SBMLfieldnames =

     []

Error using OutputSBML

First input must be a valid MATLAB_SBML Structure

Errors reported: fbc_objective structure reports fbc_objective level mismatch
USAGE: OutputSBML(SBMLModel, (filename), (exclusiveFlag), (applyUserValidation))

Error in exportModel (line 670)
OutputSBML(modelSBML,fileName,1,0,[1,0]);

Error in exportModelxml (line 16)
exportModel(modelRAVEN2,'reh16_V13.xml');

**Comment by edkerk** [comment] 2021-11-04 07:54
Is any reaction set as objective function? `find(modelRAVEN2.c)`

**Comment by mascencio27** [comment] 2021-11-04 13:06
Thanks you for your response.

Yes.

find(modelRAVEN2.c)

ans =

        2752
        2865
        2866
        2867
        2868
        2869
        2870
        2871
        2872
        2873
        2874
        2875
        2876
        2877
        2878
        2879
        2880
        2881
        2882
        2883
        2884
        2885
        2886
        2887
        2888

**Comment by mascencio27** [comment] 2021-11-04 13:44
Dear Eduard.

The problem is solved. Sure enough I had more than one objective function, by modifying the file it was possible to convert it to xml.

Thanks for your great help.

Greetings

**Comment by edkerk** [comment] 2021-11-04 13:54
Good to know that SBML FBCv2 does not allow for multiple objective functions, we'll include this check in RAVEN.

It seems that all RAVEN-related problems are solved, so I will close this issue. If you run into any other problems, feel free to open a new issue!

**Closed by edkerk** 2021-11-04 13:54 UTC
Labels: help wanted
