### ISSUE TITLE
Can fast tINIT integrate data from bulk RNA-seq?

### ISSUE THREAD

**Issue by yangjingyu1108** [SysBioChalmers/RAVEN#518] opened 2023-12-19 01:48 UTC
#### Current behavior:

We used fast tINIT to integrate different bulk RNA-seq (Hart2015_RNAseq; K562, GEO: GSE71299). Both failed to run successfully and showed the same results as shown in  figures.
![图片1](https://github.com/SysBioChalmers/Human-GEM/assets/140698322/c3c0a53d-0ec9-4c54-9a9e-0434988570f5)
<img width="437" alt="图片2" src="https://github.com/SysBioChalmers/Human-GEM/assets/140698322/4b841c78-8a3f-41b7-8f6b-8cdbc395ac73">

#### Expected feature/value/output:

I want to know why.

**Comment by edkerk** [comment] 2024-01-15 11:45
@yangjingyu1108 Which solver do you use?

**Comment by yangjingyu1108** [comment] 2024-01-18 05:55
> @yangjingyu1108 Which solver do you use?

RAVEN.

**Comment by mihai-sysbio** [comment] 2024-01-18 08:44
> > @yangjingyu1108 Which solver do you use?
> 
> RAVEN.

The RAVEN toolbox can work with different solvers. This info is shown in the output of the command `checkInstallation`. Could you paste that output here please?

**Comment by yangjingyu1108** [comment] 2024-01-19 01:23
> > > @yangjingyu1108 Which solver do you use?
> > 
> > 
> > RAVEN.
> 
> The RAVEN toolbox can work with different solvers. This info is shown in the output of the command `checkInstallation`. Could you paste that output here please?

>> checkInstallation

*** THE RAVEN TOOLBOX ***

 > Checking RAVEN release               2.7.5
   > Checking for latest RAVEN release  Fail
     Cannot reach GitHub for release info
 > Checking MATLAB release              2023a
 > Set RAVEN in MATLAB path             Pass

=== Model import and export ===
 > Add Java paths for Excel format      Pass
 > Checking libSBML version             5.19.0
 > Checking model import and export
   > Import Excel format                Pass
   > Export Excel format                Pass
   > Import SBML format                 Pass
   > Export SBML format                 Pass

=== Model solvers ===
 > Checking for LP solvers
   > glpk                               Pass
   > gurobi                             Pass
   > cobra                              Pass
 > Checking for MILP solvers
   > glpk                               Pass
     While passing here, we do not recommended glpk
     for MILPs due to occasional inconsistent results
   > gurobi                             Pass
   > cobra                              Pass
 > Set RAVEN solver                     gurobi

=== Essential binary executables ===
 > Checking BLAST+                      Pass
 > Checking DIAMOND                     Pass
 > Checking HMMER                       Pass

=== Compatibility ===
 > Checking function uniqueness         Fail
   Duplicate functions in C:\Users\jjyan\Documents\GitHub\Human-GEM\code\GPRs
     getGenesFromGrRules.m
   Duplicate functions in C:\Users\jjyan\Documents\GitHub\Human1_Publication_Data_Scripts\tINIT_GEMs\figures
     compareMultipleModels.m
   Duplicate functions in C:\Users\jjyan\Documents\GitHub\yjy\code
     simplifyModel.m
   Duplicate functions in C:\Users\jjyan\Documents\GitHub\ftINIT-Human-GEM\code\GPRs
     getGenesFromGrRules.m
   Resolve conflicting functions to ensure RAVEN functionality

*** checkInstallation complete ***

>>

**Comment by mihai-sysbio** [comment] 2024-01-23 07:37
@yangjingyu1108 the version of RAVEN you are using looks surprisingly old - 2.7.5 was released Jun 28, 2022. Could you please update to the latest 2.8.6 https://github.com/SysBioChalmers/RAVEN/wiki/Installation#installation ? I kind of lost track of what was done in which release, but this is any thing to check. 
Could you also please share the _version_ of Gurobi you are using? It's normally included in the license file.

**Comment by edkerk** [comment] 2024-01-24 13:22
Indeed, there are some significant changes related to the solver and ftINIT that might have to do with the error you encounter. So please update your RAVEN version, and if the error persist, then also report the Gurobi version.

**Comment by edkerk** [comment] 2024-02-07 19:47
I can report first-hand that using bulk-RNAseq with ftINIT should work, so it is likely that the error is caused by using an older RAVEN release. I will close this issue, can be reopened if the problem persists in release 2.8.6+.

**Closed by edkerk** 2024-02-07 19:47 UTC
Labels: bug
