### ISSUE TITLE
chore: DIAMOND error 255

### ISSUE THREAD

**Issue by NagihanMatlab** [SysBioChalmers/RAVEN#322] opened 2020-12-07 11:36 UTC
### Description of the issue:
```matlab
Error using dispEM (line 47)
DIAMOND makedb did not run successfully, error: 255

Error in getDiamond (line 85)
dispEM(EM,true);

Error in getMetaCycModelForOrganism (line 90)
blastStruc=getDiamond(organismID,fastaFile,{'MetaCyc'},fullfile(ravenPath,'metacyc','protseq.fsa'));
```
#### Reproducing this issue:
```matlab
ScoMetaCycDraftModel=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.faa',1); 
```

#### System information
* Please report:
1. RAVEN version: 2.4.2
2. Operating system: Windows 8

**I hereby confirm that I have:**
- [x] Followed the [guidelines](https://github.com/SysBioChalmers/RAVEN/wiki/Installation) to install RAVEN.
- [ ] Checked that a similar issue does not [already exist](https://github.com/SysBioChalmers/RAVEN/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] If suitable, needed, asked first in the [Gitter chat room](https://gitter.im/SysBioChalmers/RAVEN) about the issue

**Comment by simas232** [comment] 2020-12-07 12:50
@NagihanMatlab, you should firstly finalise editing the given Issue template. Edit it and let us know thereupon. Also, make sure that you are familiar with the requirements checklist given in the bottom of the template. We will try to help to resolve your issue then.

**Comment by NagihanMatlab** [comment] 2020-12-07 13:05
When I run this command, it outputs "DIAMOND makedb did not run successfully, error: -107374151"

**Comment by edkerk** [comment] 2020-12-07 14:05
@NagihanMatlab If you click on the three dots next to the smiley that is above your original post, you can select to edit your first post. Please provide more information on what command you're trying to run, what operating system you are working on, version of MATLAB, version of RAVEN, explanation of what you have tried yourself. With the current information that you provide we cannot help you to find out what is the problem. Also, you can just leave the issue open until it is resolved, we can also close it by then.

**Comment by NagihanMatlab** [comment] 2020-12-07 18:45
Operating system: Windows8, Matlab version: R2020a, Raven version :2.4.1
 I tried to run ScoMetaCycDraftModel=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.faa',1); and the output was 
Error using dispEM (line 47)
DIAMOND makedb did not run successfully, error: 255


Error in getDiamond (line 85)
    dispEM(EM,true);

Error in getMetaCycModelForOrganism (line 90)
    blastStruc=getDiamond(organismID,fastaFile,{'MetaCyc'},fullfile(ravenPath,'metacyc','protseq.fsa'));

**Comment by simas232** [comment] 2020-12-07 19:07
@NagihanMatlab, could you please run `[success,blastStructure]=testDiamond();` and let me know the value of `success` output parameter? If you get any errors, you can write paste them as well.

**Comment by NagihanMatlab** [comment] 2020-12-07 19:33
[success,blastStructure]=testDiamond();
Testing DIAMOND makedb... Not OK
Error using dispEM (line 47)
DIAMOND makedb did not run successfully, error: 255

Error in testDiamond (line 79)
        dispEM(EM,true);

**Comment by simas232** [comment] 2020-12-07 20:04
@NagihanMatlab, thank you for an output. This error clearly indicates that this is a DIAMOND, not RAVEN issue. My first advice would be to test the newest DIAMOND version (just replace `diamond.exe` with the new file in `RAVENdir/software/diamond/`) and if it does not work then test the oldest versions, starting with `v0.7.3` since it is likely that newest DIAMOND versions are no longer compatible with Windows 8. If this still does not work, then contact the developer via Issues in DIAMOND GitHub repository. Also, please write whether you are able to ensure DIAMOND functionality in your machine.

P.S. As an alternative, you can try running GEM reconstruction from MetaCyc using BLAST+ instead even though it will be slower. For further info have a look in `useDiamond` parameter description.

**Comment by NagihanMatlab** [comment] 2020-12-07 20:09
Thank you.

7 Ara 2020 Pzt 23:05 tarihinde Simonas Marcišauskas <
notifications@github.com> şunu yazdı:

**Comment by Hao-Chalmers** [comment] 2020-12-07 20:33
@NagihanMatlab as suggested by @simas232 , the error you reported can be circumvented by using BLAST with following command:
`ScoMetaCycDraftModel=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.faa',true,false,false,100,45,false);`

**Comment by NagihanMatlab** [comment] 2020-12-07 20:36
Thank you so much.I'll try it.

7 Ara 2020 Pzt 23:33 tarihinde Hao Wang <notifications@github.com> şunu
yazdı:

**Comment by NagihanMatlab** [comment] 2020-12-08 18:00
I ran the "ScoMetaCycDraftModel=getMetaCycModelForOrganism('ScoMetaCyc','Sco_all_protein.faa',true,false,false,100,45,false);" command but the output did not change. Thank you. I will try to use the old versions of the diamond.

Error using dispEM (line 47)
makeblastdb did not run successfully, error: 1


Error in getBlast (line 84)
    dispEM(EM,true);

Error in getMetaCycModelForOrganism (line 92)
    blastStruc=getBlast(organismID,fastaFile,{'MetaCyc'},fullfile(ravenPath,'metacyc','protseq.fsa'));

**Comment by simas232** [comment] 2020-12-08 20:40
Hm, I feel more and more suspicious about Windows 8 compatibility. Let's see if older DIAMOND versions resolve this issue.

**Comment by edkerk** [comment] 2021-02-09 13:36
Duplicate of #306.

**Closed by edkerk** 2021-02-09 13:36 UTC
Labels: duplicate
