### ISSUE TITLE
The problem with exportToExcelFormat()

### ISSUE THREAD

**Issue by amirfeizi** [SysBioChalmers/RAVEN#3] opened 2016-10-14 10:42 UTC
Hi Daniel,

I have been using exportToTabDelimite() to get an excel file out puts from "iAdipocytes1809.xlm". The function give an error of as below

>>exportToExcelFormat(model,'iAdipocytes1809.xls')

Error: File: exportToExcelFormat.m Line: 37 Column: 43
Unbalanced or unexpected parenthesis or bracket.
 
I checked the function documentation and it seemed it needs to provide a path for the directory to save which I did but it did give me the same error.

Then instead I used the exportToTabDelimited() function instead and it worked fine but the output files while it has the same structure of the models in excel format yet it also has a lot of html and SBML tags in in reaction pages which makes it difficult to follow up.

I would appreciate if you consider resolving the export functions problems to convert the model to the proper excel  format.

Best,

Amir

**Comment by zertan** [comment] 2016-10-21 19:09
This seems to be a duplicate of issue #2. Please do a 'git pull' to get an updated repo. We'll also delve deeper into import/export in the future!

**Closed by zertan** 2016-10-21 19:09 UTC
Labels: duplicate
